def on_button_pressed_a():
    music.play_tone(220, music.beat(BeatFraction.WHOLE))
    music.play_tone(247, music.beat(BeatFraction.HALF))
    music.play_tone(220, music.beat(BeatFraction.HALF))
    basic.pause(50)
    music.play_tone(247, music.beat(BeatFraction.WHOLE))
    music.play_tone(220, music.beat(BeatFraction.HALF))
    music.play_tone(247, music.beat(BeatFraction.HALF))
    music.play_tone(220, music.beat(BeatFraction.HALF))
    basic.pause(50)
    music.play_tone(262, music.beat(BeatFraction.WHOLE))
    music.play_tone(247, music.beat(BeatFraction.HALF))
    music.play_tone(262, music.beat(BeatFraction.HALF))
    music.play_tone(247, music.beat(BeatFraction.HALF))
    basic.pause(50)
    for index in range(2):
        music.play_tone(294, music.beat(BeatFraction.WHOLE))
        music.play_tone(262, music.beat(BeatFraction.HALF))
        music.play_tone(294, music.beat(BeatFraction.HALF))
        music.play_tone(262, music.beat(BeatFraction.HALF))
        basic.pause(50)
    music.play_tone(294, music.beat(BeatFraction.WHOLE))
    music.play_tone(262, music.beat(BeatFraction.HALF))
    music.play_tone(294, music.beat(BeatFraction.HALF))
    music.play_tone(262, music.beat(BeatFraction.HALF))
    music.play_tone(247, music.beat(BeatFraction.HALF))
    music.play_tone(220, music.beat(BeatFraction.HALF))
    basic.pause(50)
    music.play_tone(208, music.beat(BeatFraction.HALF))
    basic.pause(50)
    music.play_tone(220, music.beat(BeatFraction.HALF))
    music.play_tone(247, music.beat(BeatFraction.HALF))
    music.play_tone(220, music.beat(BeatFraction.HALF))
    basic.pause(100)
    music.play_tone(262, music.beat(BeatFraction.WHOLE))
    music.play_tone(247, music.beat(BeatFraction.HALF))
    music.play_tone(262, music.beat(BeatFraction.HALF))
    music.play_tone(247, music.beat(BeatFraction.HALF))
    music.play_tone(220, music.beat(BeatFraction.HALF))
    music.play_tone(208, music.beat(BeatFraction.HALF))
    basic.pause(200)
    for index2 in range(3):
        music.play_tone(262, music.beat(BeatFraction.HALF))
        music.play_tone(247, music.beat(BeatFraction.HALF))
        music.play_tone(220, music.beat(BeatFraction.HALF))
    music.play_tone(262, music.beat(BeatFraction.HALF))
    music.play_tone(247, music.beat(BeatFraction.HALF))
    music.play_tone(220, music.beat(BeatFraction.HALF))
    music.play_tone(165, music.beat(BeatFraction.HALF))
    music.play_tone(165, music.beat(BeatFraction.HALF))
    music.play_tone(165, music.beat(BeatFraction.HALF))
    for index3 in range(3):
        music.play_tone(196, music.beat(BeatFraction.HALF))
    music.play_tone(185, music.beat(BeatFraction.HALF))
    music.play_tone(175, music.beat(BeatFraction.DOUBLE))
    for index4 in range(3):
        music.play_tone(262, music.beat(BeatFraction.HALF))
        music.play_tone(247, music.beat(BeatFraction.HALF))
        music.play_tone(220, music.beat(BeatFraction.HALF))
    basic.pause(100)
    music.play_tone(294, music.beat(BeatFraction.HALF))
    music.play_tone(262, music.beat(BeatFraction.HALF))
    music.play_tone(247, music.beat(BeatFraction.HALF))
    basic.pause(12)
    music.play_tone(247, music.beat(BeatFraction.HALF))
    music.play_tone(262, music.beat(BeatFraction.HALF))
    music.play_tone(294, music.beat(BeatFraction.HALF))
    music.play_tone(330, music.beat(BeatFraction.HALF))
    music.play_tone(294, music.beat(BeatFraction.HALF))
    music.play_tone(262, music.beat(BeatFraction.HALF))
    music.play_tone(247, music.beat(BeatFraction.HALF))
    music.play_tone(220, music.beat(BeatFraction.DOUBLE))
input.on_button_pressed(Button.A, on_button_pressed_a)

def on_sound_loud():
    pass
input.on_sound(DetectedSound.LOUD, on_sound_loud)

def on_button_pressed_b():
    music.set_volume(255)
    music.play_tone(349, music.beat(BeatFraction.WHOLE))
    music.play_tone(262, music.beat(BeatFraction.HALF))
    music.play_tone(349, music.beat(BeatFraction.HALF))
    music.play_tone(440, music.beat(BeatFraction.HALF))
    music.play_tone(349, music.beat(BeatFraction.HALF))
    music.play_tone(440, music.beat(BeatFraction.HALF))
    music.play_tone(587, music.beat(BeatFraction.HALF))
    music.play_tone(523, music.beat(BeatFraction.HALF))
    basic.pause(20)
    music.play_tone(523, music.beat(BeatFraction.QUARTER))
    basic.pause(20)
    music.play_tone(523, music.beat(BeatFraction.QUARTER))
    for index5 in range(3):
        basic.pause(20)
        music.play_tone(523, music.beat(BeatFraction.HALF))
    music.play_tone(262, music.beat(BeatFraction.HALF))
    music.play_tone(349, music.beat(BeatFraction.HALF))
    music.play_tone(392, music.beat(BeatFraction.HALF))
    music.play_tone(440, music.beat(BeatFraction.WHOLE))
    basic.pause(20)
    music.play_tone(440, music.beat(BeatFraction.WHOLE))
    basic.pause(20)
    music.play_tone(440, music.beat(BeatFraction.HALF))
    music.play_tone(392, music.beat(BeatFraction.HALF))
    music.play_tone(349, music.beat(BeatFraction.HALF))
    music.play_tone(330, music.beat(BeatFraction.HALF))
    music.play_tone(349, music.beat(BeatFraction.WHOLE))
    basic.pause(20)
    music.play_tone(349, music.beat(BeatFraction.WHOLE))
    basic.pause(20)
    music.play_tone(349, music.beat(BeatFraction.HALF))
    music.play_tone(330, music.beat(BeatFraction.HALF))
    music.play_tone(294, music.beat(BeatFraction.HALF))
    music.play_tone(262, music.beat(BeatFraction.HALF))
    music.play_tone(294, music.beat(BeatFraction.WHOLE))
    music.play_tone(262, music.beat(BeatFraction.WHOLE))
    basic.pause(20)
    music.play_tone(262, music.beat(BeatFraction.HALF))
    music.play_tone(349, music.beat(BeatFraction.HALF))
    music.play_tone(392, music.beat(BeatFraction.HALF))
    music.play_tone(349, music.beat(BeatFraction.HALF))
    music.play_tone(330, music.beat(BeatFraction.BREVE))
    music.play_tone(262, music.beat(BeatFraction.HALF))
    music.play_tone(330, music.beat(BeatFraction.HALF))
    music.play_tone(349, music.beat(BeatFraction.HALF))
    music.play_tone(392, music.beat(BeatFraction.WHOLE))
    music.play_tone(330, music.beat(BeatFraction.WHOLE))
    music.play_tone(349, music.beat(BeatFraction.WHOLE))
    music.play_tone(392, music.beat(BeatFraction.WHOLE))
    music.play_tone(440, music.beat(BeatFraction.WHOLE))
    music.play_tone(587, music.beat(BeatFraction.QUARTER))
    music.play_tone(523, music.beat(BeatFraction.DOUBLE))
    basic.pause(100)
    music.play_tone(440, music.beat(BeatFraction.WHOLE))
    basic.pause(20)
    music.play_tone(392, music.beat(BeatFraction.QUARTER))
    music.play_tone(523, music.beat(BeatFraction.DOUBLE))
    basic.pause(100)
    music.play_tone(262, music.beat(BeatFraction.WHOLE))
    music.play_tone(330, music.beat(BeatFraction.WHOLE))
    music.play_tone(392, music.beat(BeatFraction.WHOLE))
    music.play_tone(349, music.beat(BeatFraction.DOUBLE))
    music.play_tone(466, music.beat(BeatFraction.WHOLE))
    music.play_tone(587, music.beat(BeatFraction.DOUBLE))
    music.play_tone(523, music.beat(BeatFraction.WHOLE))
    music.play_tone(494, music.beat(BeatFraction.WHOLE))
    music.play_tone(523, music.beat(BeatFraction.WHOLE))
    music.play_tone(262, music.beat(BeatFraction.HALF))
    music.play_tone(330, music.beat(BeatFraction.HALF))
    music.play_tone(349, music.beat(BeatFraction.HALF))
input.on_button_pressed(Button.B, on_button_pressed_b)
